### ISSUE TITLE
Ikke slette annen context data

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#115]
Hvis man først leverer data på `context == caregiver` og så senere leverer data på `context == recident` vil de første dataene bli slettet.

**Comment by areedv** [comment]
Er det best at du @arnfinn tester dette med dine data, eller vil du at jeg skal gjøre det?

**Comment by arnfinn** [comment]
Denne ligger data her du kan teste med: https://github.com/mong/qmongrdata-raw/tree/master/Hjerteinfarkt

beh.csv og bo.csv
