### ISSUE TITLE
Åpne "Send feilmelding til SKDE" i nytt vindu

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#126]
Så slipper bruker å bli kastet ut av appen.

**Comment by areedv** [comment]
Hos meg åpnes bare epost-klienten... Antar at "kastet ut" ikke betyr at du må logge inn på nytt?

**Comment by arnfinn** [comment]
Nei, logges ikke ut. Er sikker bare jeg som ikke har installert noe epost-klient.

Dette er ikke en oppgave som må prioriteres:)

**Comment by areedv** [comment]
Kan være like irriterende med et nytt, tomt nettleservindu hvis man blir sendt til en epost-klient. Vi kan basere ev tiltak på en rask intern gjennomgang av brukeropplevelser

**Comment by areedv** [comment]
Åpne igjen hvis det faktisk er et problem
