### ISSUE TITLE
Hvorfor kan `var` kun være heltall? 

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#127]
Jeg får følgende melding når jeg prøver å levere data fra kreftregister:

```
En eller flere verdier i var er ikke naturlige tall (inkludert 0) ''
```

De har utregnet prosent i `var`.

**Comment by areedv** [comment]
Det ble på et tidspunkt satt og implementer som en regel. Ser at data-tabellen åpner for DOUBLE(9,3) og det betyr at det allerede er åpning for desimaltall på begge sider av 0. Det viktigste er vel at vi vet hvilke følger en ev endring av reglene vil få
