### ISSUE TITLE
Bruke name som unik id i registry-tabell

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#129]
`name` må være unik for at app skal fungere. Det er også tungvint å måtte finne `id`-nummer på register hver gang man skal legge inn oppdaterte indikatorbeskrivelser.

**Comment by areedv** [comment]
Alternativt kan `registry_name` legges til som et felt i ind-tabellen. `name` er forøvrig allerede definert som unikt i registry-tabellen og datamodellen forbyr således duplikater i dette feltet (uavhengig av app-en)

**Comment by areedv** [comment]
Det finnes nå et eget gui i imongr for redigering av indikatorer
