### ISSUE TITLE
Feil målnivå-farge hvis målnivå == 0 

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#132]
![image](https://user-images.githubusercontent.com/136346/122899607-41cf1e00-d34c-11eb-8c57-d78b6bca1ba6.png)

**Comment by areedv** [comment]
Ingen farger i imongr... Hvilke verdi (i agg data) er det disse observasjonene tildeles?

**Comment by arnfinn** [comment]
Gjelder definisjonen av `level` i `agg_data`. Skal settes til `M` i dette tilfelle, men settes til `H`. Sannsynligvis på grunn av avrunding.

https://github.com/mong/imongr/blob/eabfbc1463ba15448a1224148fae2a299493b610/R/aggregate.R#L442

**Comment by areedv** [comment]
As of #122
