### ISSUE TITLE
Size limit?

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#14]
![Screenshot 2020-06-22 at 09 48 57](https://user-images.githubusercontent.com/136346/85262163-ade32180-b46d-11ea-9ee2-b14faa0f80f5.png)

**Comment by areedv** [comment]
Yes, there is a limit both in lb-rp and shinyproxy, maybe also in shiny... What is the size of this file?

**Comment by arnfinn** [comment]
21.6 MB. The file is in the `qmongrdata` package.

**Comment by areedv** [comment]
Probably to be fixed in https://github.com/mong/lb-rp

**Comment by areedv** [comment]
Please check if above changes fix issue
