### ISSUE TITLE
Mulig å publisere kun indikatorbeskrivelse-oppdatering, hvis kun dette er oppdatert

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#149]
Hvis man har oppdatert indikatorbeskrivelsen men ikke oppdatert rådataene får man ikke lov å levere denne oppdateringen, siden latest er satt til `1` i `delivery`-tabellen. Det burde være mulig å kun oppdatere indikatorbeskrivelsen (aggregeringen burde da kjøres på nytt siden måloppnåelse defineres under aggregeringen og målnivå kan være endret).

**Comment by areedv** [comment]
En mulighet her er at indikatorbeskrivelsene betraktes som en del av datasettet. Pt hindres leveranse hvis (en hash av) datasettet er lik (hashverdien av) forrige leveranse og det kan hende at også indikatorbeskrivelsene kan tas med i denne betraktningen. En veldig begrenset endring vil da muligens åpne for at data kan leveres på nytt uten at tallene i seg selv er endret. Trenger nok uansett litt nærmere gjennomgang

**Comment by areedv** [comment]
Det er opplagt et behov for å kunne endre tekster uten at data endres. Betrakter derfor dette som en feil fra nå av...
