### ISSUE TITLE
Definere `latest` per register og ikke per bruker

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#150]
`latest` blir satt til 1 i `delivery`-tabellen per bruker, så hvis samme bruker leverer data til annet register vil den bli satt til 0 for det første registeret (og man kan da levere samme data på nytt til første register).

**Comment by areedv** [comment]
```latest``` er et overflødig felt i tabellen og er egentlig ikke særlig nyttig for noe. Her er formålet at data skal kunne leveres når de er endret på og det kan sannsynligvis fikses på annet vis, se #149. Hvis denne antagelsen ikke holder så får heller saken gjenåpnes.

**Comment by arnfinn** [comment]
Jeg syns egentlig den bare har vært en plage:) Har du mulighet til å slå av denne sjekken? Eventuelt (og kanskje det beste) at det bare kommer en advarsel om at datasettet er likt, men at det fremdeles vil være mulig å levere data.

**Comment by areedv** [comment]
Joda, en sjekkliste skal per definisjon være en "plage" :wink: Her er det snakk om å kunne levere data på en fornuftig måte og det tror jeg vi fint kan ta høyde for i #149 Ellers skal en sjekkliste være boolsk, altså ikke noe fuzzy logic...
