### ISSUE TITLE
Mulig å laste opp ikke-komplette datasett (halvårlig etc)

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#163]
Vi må kunne vise resultater for siste år som ikke er komplette. Disse skal vises på nettsiden som stiplet linje. Vi må derfor også kunne vite om siste år er komplett eller ikke.

## Mulige løsninger

- Et ekstra felt i indikatortabellen som viser hvilket år som er siste kvalitetssikret år. Hvis denne er satt til `2020` vil alle data med `year = 2021` og høyere vises som stiplet linje.
- Et ekstra felt i indikatortabellen med dato for siste gjeldende observasjon. Dette kan så oppgis i indikatorbeskrivelsen.

Mulig man også kan tenke seg en kombinasjon av disse, eller noe helt annet.

Vi må ha på plass dette før vi kan implementere noe på `qmongjs`-siden.

**Comment by arnfinn** [comment]
En reell `use case`: Jeg har mottatt data for 2021 frem til og med 1. juni for protese-, hoftebrudd-, og korsbåndsregisteret. Det er nå et krav for å havne på høyeste nivå (nivå 5?) at registeret publiserer data hyppigere enn en gang i året.

**Comment by areedv** [comment]
Kan løses ved at bruker ved opplasting manuelt angir dato for når siste observasjon (indikator) er gjort? Jf diskusjon i møte 27. jan 22.

**Comment by areedv** [comment]
## Forslag til løsning

### GUI
Ved opplasting av fil med indikatorer (til verify) gis det to nye valg:
1. "Datasettet er oppdatert per:" [_valgbart datofelt preutfylt med dagens dato_]
2. "Merk datasettet som foreløpig etter:" [_valgbart datofelt preutfylt med dagens dato_]

Videre bør det lages mer tekst i veiledningen som forklarer disse to datovalgene.

### Database
Nye felter etableres:
1. `delivery.latest_update` DATETIME
2. `delivery.latest_affirm` DATETIME
3. `agg_data.delivery_latest_update` DATETIME
4. `agg_data.delivery_latest_affirm` DATETIME


### App
Ved opplasting av data skrives 1 og 2 inn i `delivery` på samme måte som eksisterende felter fylles ut. Rett etter aggregering skrives 3 og 4 inn i `agg_data` basert på samme metode som for `agg_data.delivery_time`. Her må det lages noen nye funksjoner som ivaretar akkurat dette behovet.

### Diskusjon
Her er det antatt at ny informasjon til `qmongjs` best ivaretas gjennom `agg_data`. Dette er basert på at `delivery_time` allerede er der og at denne tabellen er løsrevet fra resten av datamodellen og dermed bedre egnet til å oppdateres/gjenskapes. Om man heller vil benytte `ind` så bør ev sideeffekter av dette vurderes mer grundig.

**Comment by areedv** [comment]
Se på ev bruk av dato fra verify.agg_data fordi den er mer riktig mtp faktisk levering og dermed siste gang oppdatert...

**Comment by arnfinn** [comment]
Legge datoer inn i `indikator`-tabell? Denne blir overført til prod ved publisering.

**Comment by areedv** [comment]
Etter litt tenking:
- vil ikke bruke tidsangivelse fra agg_`data.time` fordi denne er "nedstrøms" og endres vilkårlig (hver gang noen finner ut at de skal kjøre en ny agg)
- vil ikke bruke `ind`-tabellen for å "huse" de nye tidsangivelsen fordi det kun er tekstene som idag oppdateres ved "publish" (og ikke hele tabellen)

I stort skyldes disse valgene at integriteten i gjeldende datamodell må ivaretas, og da er det utfordrende med "isolerte" oppdateringer løsrevet fra resten av datamodellen. Prosjektet har nå "sklidd" ifra opprinnelig design, dvs at behovet egentlig kun er å ivareta `agg_data` i PROD. Vi kan gjerne gå dit, men det betyr i så fall en mer fundamental endring.
