### ISSUE TITLE
Problemer hvis type er forskjellig mellom prod og verify

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#211]
Se epostutveksling med Lena i uke 33/34 angående indikator `nger_pasient_tilfredshet`.

Verify hadde `type == "gjennomsnitt"` og kjører dermed ingen aggregeringer opp til nasjonalt nivå eller beregning av andel:

![image](https://user-images.githubusercontent.com/136346/185860161-a0960b60-ebc5-451b-9412-2d63f7f0d11c.png)

Prod hadde `type == "andel"` og aggregerte opp og beregnet andel på verdier som ikke ga mening (usikker på hvor disse verdiene kom fra).

![image](https://user-images.githubusercontent.com/136346/185860061-586753a8-6598-4730-a7a7-7a311f281cbc.png)

Tilfeldig datarad på verify:
![image](https://user-images.githubusercontent.com/136346/185861155-77b2a59f-401e-4d3d-b350-c3f132e66969.png)
Samme rad på prod:
![image](https://user-images.githubusercontent.com/136346/185861204-06924b6a-b59e-446e-a687-bcba43812704.png)

**Comment by arnfinn** [comment]
Mulig dette allerede er fikset? Om `type` oppdateres på `prod` før data lastes over?

**Comment by areedv** [comment]
`type` er en del av publisering i den versjonen som ligger i QA og denne må gjerne benyttes nå for å avdekke mangler eller feil for ev oppretting før neste versjon legges ut i PROD

**Comment by arnfinn** [comment]
Funker fint.
