### ISSUE TITLE
Mulighet til å velge register på forsiden

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#221]
som så går igjen i alle fanene, slik at man slipper å stadig velge riktig register ved bytte av fane.

@lenaringstado stemmer denne beskrivelsen?

**Comment by lenaringstado** [comment]
Høres veldig bra ut!

**Comment by Stein-Kato** [comment]
Hadde det fungert hvis man beholdt valgt register når man bytter fane uten at grensesnittet endres? 
@lenaringstado @arnfinn

**Comment by arnfinn** [comment]
> Hadde det fungert hvis man beholdt valgt register når man bytter fane uten at grensesnittet endres? @lenaringstado @arnfinn

Ja:)

**Comment by lenaringstado** [comment]
Veldig gjerne! Det er irriterende at man alltid må velge bort hjerneslag når man skal gjøre noe, selv om man valgte det registeret man jobber med på forrige side.
