### ISSUE TITLE
Mulige duplikater i agg_data

### ISSUE THREAD

**Issue by areedv** [mong/imongr#229]
på "hospital" nivå. Sett bla på nkr under gjennomgang ifm med uttrekk til Marianne

**Comment by Stein-Kato** [comment]
Dekningsgrad er registrert flere ganger for samme år i NKR-rygg. Dette lager krøll i aggregeringen.

**Comment by Stein-Kato** [comment]
@arnfinn Kan vi lukke denne?

**Comment by arnfinn** [comment]
@Stein-Kato Ja:)
