### ISSUE TITLE
Fjerne "level" og "level_direction" fra agg_data i databasene

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#255]
Disse er overflødig, men legges på i `imongr` under aggregeringen for å ikke få en kræsj.

Etter at en har fjernet `level` og `level_direction` fra både prod og verify, må det gjøres endringer i `imongr` og disse må publiseres. Det vil ikke være mulig å levere data før endringene er gjort (og publisert).

- [x] Fjerne felt i database verify
- [x] Fjerne felt i database prod
- [x] Fjerne kallet på `get_indicator_level` i `agg`-funksjonen (linje 144 i `aggregate.R`)
- [x] Fjerne `level` og `level_direction` fra `db$tab$agg_data$insert` i `imongr.yml`-konfigurasjonsfil.
- [x] Lage ny publikasjon av `imongr`

**Comment by arnfinn** [comment]
@areedv Høres dette trygt og greit ut?

**Comment by areedv** [comment]
Alle muligheter til å finne ut av det i utviklingsmiljøet, til og med med mulighet for å rulle tilbake :roller_coaster:

**Comment by arnfinn** [comment]
Ikke helt ferdig å rydde i db + publisere ny versjon.

**Comment by Stein-Kato** [comment]
imongr kræsjer nå på grunn av "level"-kolonnen (#353). Foreslår at vi sletter "level" og "level_direction" i databasene. Opplasting, publisering og reaggregering fungerer fint uten disse.

**Comment by arnfinn** [comment]
Fikset i database og versjon https://github.com/mong/imongr/releases/tag/v2.0.0
