### ISSUE TITLE
Må ha samme `delivery_latest_update`-dato på `verify` og `prod`

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#284]
De som laster opp data kan definere denne datoen selv. **Alle indikatorer er oppdatert per:** er den datoen som settes i databasen som `delivery_latest_update` på `verify`. Når data publiseres, settes en ny dato her (dagens dato).

![image](https://github.com/mong/imongr/assets/136346/a6560d29-9342-485d-932e-299917862a41)

Siden dette er en dato satt av bruker, må denne også leves *as is* til `prod`.

**Comment by Stein-Kato** [comment]
### Databasetruktur

I databasen er `data`-tabellen koblet til `delivery`-tabellen via `delivery_id`-kolonnen , og `delivery`-tabellen er koblet til `user_registry`-tabellen via `user_id`-kolonnen. I `user_registry`-tabellen er hver bruker knyttet til ett eller flere registre via `registry_id`-kolonnen. 

![image](https://github.com/mong/imongr/assets/64078729/249f68ba-746f-4373-8947-778c359cd3f8)

### Beskrivelse av problemet

`delivery` vet ikke hvilket register det leverer data til, men det vet hvilken bruker som har levert dataen, så det må innom `user_registry` for å sjekke hvilket register brukeren er knyttet til. I tillegg er det en kolonne i `delivery`som heter `latest` som settes til 1 hvis dette er brukerens siste levering. 

Funksjonen `get_registry_latest_delivery` i `db_get.R` skal hente siste ´delivery' til et gitt register slik at man kan hente ut datoen for leveringen når data publiseres. SQL-spørringen er: 

`SELECT
  d.*
FROM
  user_registry AS ur
LEFT JOIN delivery AS d ON
  ur.user_id = d.user_id
WHERE
  d.latest = 1 AND
  ur.registry_id = @registry_id
ORDER BY
  d.time DESC;`

og man henter ut øverste rad som siste leveranse. Her kan det oppstå problemer dersom: 

1. Brukeren leverer data til flere registre før publisering
2. Det er ikke samsvar mellom bruker og register i `user_registry`

I tilfelle 1 vil `latest` være 1 kun i siste leveranse for denne brukeren. Funksjonen vil derfor returnere siste leveranse for brukeren, og datoen på alle publiseringene vil derfor bli den samme uavhengig av registeret som brukeren publiserer til. 

I tilfelle 2 vil funksjonen returnere siste leveranse fra brukeren som er knyttet til registeret man filtrerer på og som har levert nyligst. Det kan derfor være en tilfeldig bruker og et tilfeldig register dersom brukeren er knyttet til flere registre. 

### Mulig løsning
Istedenfor å koble `delivery` til register-id gjennom `user_id` og `latest` kunne `delivery` hatt kolonnene `registry_id` (alternativt registernavn) og `pending`. Når leveransen opprettes settes `pending` til 1, og når den publiserer endres `pending` til 0. Da kunne SQL-spørringen vært: 

`SELECT * FROM delivery WHERE registry_id = @registry_id AND pending = 1
ORDER BY time DESC;`

**Comment by arnfinn** [comment]
## Behold `delivery`-tabell som i dag

- Ved publisering hentes alle indikator-id for gitt register. Kobler delivery-id, data-tabell og indikatorer, slik at alle deliveries som er i datatabell for gitt register tas med over til prod.
- Overfør data delivery for delivery: loop over deliveries.
- Aggreger til slutt?
- Lag egen tabell for publisering, der tidspunkt, bruker-id, register-id og versjon av terms er med + hash på data/ind som er levert?.
- Kobling i delivery-tabell til publiseringstabell, hvis en delivery er publisert. Både i verify og prod.
- Register-id i publiseringstabell

**Comment by Stein-Kato** [comment]
Fikset i #299
