### ISSUE TITLE
Docker: bygge latex-dokument i eget steg

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#315]
Slik det er nå så må LaTeX være installert i det endelige imaget for at `terms.Rmd` skal bli bygd. Bedre hvis LaTeX installeres og dokumentet bygges i eget steg, og så kopiere over kun dokumentet til neste steg.

Siste steg her:
```yml
RUN R CMD INSTALL --clean ./*.tar.gz \
    && rm ./*.tar.gz \
    && R -e "rmarkdown::render(input = system.file('terms.Rmd', package = 'imongr'), output_format = 'pdf_document')"
```

Må flytte en del av koden i https://github.com/mong/imongr-base-r/blob/main/Dockerfile til dette steget. Noe ala dette:

```yml
FROM hnskde/imongr-base-r as latex

RUN apt-get update && apt-get install -y --no-install-recommends \
    pandoc \
    texlive-latex-recommended \
    texlive-latex-extra \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    && R -e "rmarkdown::render(input = system.file('terms.Rmd', package = 'imongr'), output_format = 'pdf_document')"

FROM hnskde/imongr-base-r

COPY --from=latex /pdf/file /pdf/file

...

CMD ["R", "-e", "options(shiny.port=3838,shiny.host='0.0.0.0'); imongr::run_app()"]
```

Mulig man også kunne hatt et eget image som er basert på `hnskde/imongr-base-r` der LaTeX er installert.

Vil kunne redusere størrelsen på imaget markant.

**Comment by Stein-Kato** [comment]
@arnfinn Kan vi lukke denne siden vi har gått bort fra Latex?

**Comment by arnfinn** [comment]
👍
