### ISSUE TITLE
Fjerne dummy_dg fra databasen

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#354]
Brukes ikke lenger. Test lokalt først

Dette må gjøres i prod og verify:
- [x] Fjerne fra `ind`-tabell
- [x] Fjerne alle oppføringen i `agg_data`-tabell
- [x] Sjekk at `dummy_dg` også er borte fra `data`-tabell

**Comment by Stein-Kato** [comment]
Har fjernet `dummy_dg` fra `ind`-tabellen i `verify` og `prod`. Koblede rader i `data`-tabellen ble slettet automatisk. `agg_data`-tabellen er upåvirket siden ingen indikatorer har `dummy_dg` som `dg_id`.
