### ISSUE TITLE
Meaningful information when data is uploaded

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#36]
Currently you get this:

![Screenshot from 2020-08-21 13-53-29](https://user-images.githubusercontent.com/136346/90888111-e8a5ff00-e3b5-11ea-84ca-a3f2d3cc1f4e.png)

Instead maybe remove file from `Velg fil` and show some information about your uploaded data in the main frame instead.

**Comment by areedv** [comment]
A simple approach might be a return to the initial start page...

**Comment by areedv** [comment]
For now, solved by a different message only provided for consecutive uploads, _i.e._ no error on identical data sets if there has been one or more data deliveries in between
![image](https://user-images.githubusercontent.com/1522857/92234084-b619fd00-eeb1-11ea-8a5a-8c9bbe90d651.png)
