### ISSUE TITLE
Lage versjon 2.0.1

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#368]
- [ ] Oppdater versjonsnummer i [DESCRIPTION](https://github.com/mong/imongr/blob/main/DESCRIPTION)
- [ ] Oppdatere nyheter i [NEWS.md](https://github.com/mong/imongr/blob/main/NEWS.md)
- [ ] [Lag ny release](https://github.com/mong/imongr/releases/new)

**Comment by arnfinn** [comment]
@Stein-Kato Vil du prøve deg?

**Comment by Stein-Kato** [comment]
> @Stein-Kato Vil du prøve deg?

Kan fikse det
