### ISSUE TITLE
Bruker må få beskjed hvis kolonne mangler i data

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#374]
Bruker får ingen feilmelding hvis dataene mangler kolonne `context`. Opplastingsknapp dukker ikke opp, så bruker får ikke levert inn data.

Eksempelfil:
```csv
year;orgnr;var;denominator;ind_id
2018;873255102;144;144;leddprotese_antibiotika
2018;874632562;108;115;leddprotese_antibiotika
```

**Comment by arnfinn** [comment]
Det fantes sjekk for dette men en krasj pga denne linja her fører til at de andre sjekkene ikke gjennomføres:
https://github.com/mong/imongr/blob/9ea116089d6ed2f733fa55eb8340b50a6624ed7b/R/upload.R#L351

@Stein-Kato : Denne kom inn i #307? OK å fjerne denne linja?

**Comment by Stein-Kato** [comment]
> Det fantes sjekk for dette men en krasj pga denne linja her fører til at de andre sjekkene ikke gjennomføres:
> 
> https://github.com/mong/imongr/blob/9ea116089d6ed2f733fa55eb8340b50a6624ed7b/R/upload.R#L351
> 
> @Stein-Kato : Denne kom inn i #307? OK å fjerne denne linja?

`dplyr::select(tidyselect::any_of("ind_id", "orgnr", "context", "unit_level", "year")) %>%` burde fungere hvis det mangler kolonner.

**Comment by arnfinn** [comment]
@Stein-Kato Prøvde meg på en litt annen løsning i #375. Så slipper vi å legge inn nok en pakke...
