### ISSUE TITLE
Not able to deliver twice, even if data is deleted

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#41]
Scenario:

- Day 1: User delivers OK data (`data_correct.csv`)
- Day 2: User delivers corrupt data (`data_corrupt.csv`)
- Day 3: Used finds out and wants to redeliver the same data as day 1 (`data_correct.csv`).

Currently this is not possible since "Et identisk datasett finnes allerede".

**Comment by areedv** [comment]
This is in fact an error. A reference of deprecated deliveries should not be kept but deleted as a new delivery is made.

We may also just skip this check...
