### ISSUE TITLE
Allow column names to be unquoted

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#45]
It is not possible to deliver data with column names unquoted.

This is OK
```
"orgnr";"var";"denominator";"year";"ind_id"
1;0;24;2018;colon_rapport_utredning
991324968;55;67;2018;colon_rapport_utredning
974633752;89;175;2018;colon_rapport_utredning
974705788;50;79;2018;colon_rapport_utredning
```

This is not:
TBA

**Comment by arnfinn** [comment]
Seems to be opposite when importing data directly with Adminer.

**Comment by areedv** [comment]
Currently, for upload through imongr all text is to be quoted in the csv file, also the variable names. For sure we can alter this either purely unquoted or some magic that detect whatever is submitted. However, I do not see any urgency here, so we might postpone any changes after the release of v1.0

**Comment by arnfinn** [comment]
I agree. No hurry.

**Comment by areedv** [comment]
Closing old issue. May be reopened
