### ISSUE TITLE
Aggregate on unit_name instead of orgnr?

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#46]
Several `orgnr` can point to same hospital/`unit_name`.

Probably related to https://github.com/mong/qmongr/issues/163

**Comment by areedv** [comment]
Uniqueness is enforced on ```orgnr``` only and not on ```full_name``` or ```short_name```. Hence, switching to one of the two names will eventually lead to problems/errors. If possible, I'd prefer a consistent  set of names for "Private X" across organization levels. If [the error in qmongr](https://github.com/mong/qmongr/issues/163) is due to the lack of organization X at a given year this might be solved in one or both of:
1) handle missing values in qmongr,
2) some sort of zero padding during aggregation in imongr

**Comment by arnfinn** [comment]
Jeg har nå slettet en del private i HF-dataene, og erstattet de med en som heter `999999 Private sykehus`, og satt `hf_orgnr` til `999999` for de private (og ideelle) sykehusene i sykehus-dataene. @areedv Kan du kjøre aggregering på nytt, slik at ny sykehusstruktur blir brukt?

Dette vil løse https://github.com/mong/qmongr/issues/163 men ikke problemet med at det er flere `orgnr` vi vil rute til samme `short_name`. Ett eksempel på dette er de ulike avdelingene til St. Olavs (se skjermdump). Dette gjelder også for flere andre sykehus.

![Screenshot from 2020-09-07 12-55-36](https://user-images.githubusercontent.com/136346/92380502-911fc700-f109-11ea-93ed-4b84c13beede.png)

`qmongr` har `short_name` som sitt laveste nivå. Så da må vi gjøre ett av følgende:
1. aggregere på `short_name` i stedet for `orgnr`.
2. aggregere videre i `qmongr` de sykehus/`orgnr` med samme navn.
3. kun la registre levere på ett `orgnr` (`974749025` i tilfelle St. Olavs) og ikke la de levere på andre.

**Comment by areedv** [comment]
Ok, jeg skal lage (og kjøre) en funksjon for å kunne re-aggregere alle data ute på mongr.

Til det siste så er det et brudd (i alle fall så langt jeg har forstått) med forutsetningene for sykehusviseren, altså å tillate registrering av enheter på lavere nivå enn sykehus. Vi kan selvfølgelig åpne for det også. Det vil i så fall gi mer vedlikeholdsjobb på organisasjonsstrukturen. Det bør etter min mening ikke introduseres før i v1.1+ av sykehusviseren

**Comment by areedv** [comment]
Vi lager sykehusviseren (og ikke avdelingsviseren) og da er alternativ 3 i din forrige post @arnfinn helt klart den korrekte fremgangsmåten

**Comment by arnfinn** [comment]
Må vi velge? Ett orgnummer kan kun peke på ett sykehus (men ett sykehus kan ha flere orgnr).

Vi det være mulig å først aggregere på `orgnr`, slik at man klarer å aggregere oppover i strukturen, og så etterpå aggregere på `short_name` slik at ikke `qmongr`-appen knekker sammen?

**Comment by areedv** [comment]
Nei, men vi BØR velge av to enkle grunner:
1) det er ingen konsistenssjekk på navn, _e.g._ om noen finner ut at man bør navne om en (av flere) oppføring fra _Tromsø_ til _Tromsø somatikk_, og vipps, så har vi feilaktig et nytt sykehus og der feilen ikke nødvendigvis er lett å oppdage
1) utgangspunktet/forutsetningen har hele tiden vært Sykehusviseren (og ikke Avdelingsviseren) der orgnr skulle være unik id av hver enhet på laveste nivå (jf diskusjonen om resh eller ikke) og aggregering på navn bryter med dette

Det er etter min vurdering ingen feil i hverken _qmongr_ eller _imongr_ men heller i data. Dette er forsøkt rettet i datamodellen der det nå ligger inne flere sykehus med samme navn, noe som er en "tilsnikelse" og ikke i tråd med forutsetningen. Det er en enkel sak for oss (som forvaltere av Sykehusviseren) et tilby ett orgnummer som det da må rapporteres på, også for underenheter av et gitt sykehus.

Alternativt kan vi lage enda ett nivå under sykehus. Men det vil ikke nødvendigvis løse det egentlige problemet fordi det stadig vil kunne komme inn registreringen med finere granularitet. Vi må altså uansett sette en grense og vi har fra før satt denne til sykehus.

**Comment by arnfinn** [comment]
@are Det ligger inne noen data i `data` nå med ugyldig `orgnr`. Reaggregeringen vil derfor feile. Jeg skal prøve å få fikset opp i det i morgen (CET).

**Comment by arnfinn** [comment]
Vi var vel ferdig med denne?
