### ISSUE TITLE
Missing child

### ISSUE THREAD

**Issue by areedv** [mong/imongr#48]
During debug of a failing aggregation of nkr_rygg data a child organization was found missing. Some records in the data belongs to orgnr 985962170 (MARTINA HANSENS HOSPITAL AS) which is found at the 'hf' level in our organization tree. While this should be ok for aggregation _per se_ it is not when we explode and flat out the org hierarchy. In a left join of these tables from the bottom level (hospital) and up, a missing child (_e.g._ hospital) would exclude all of its parents. Either we have to enforce children as entries are added to our organizations or we need to come up with some other solution. So far this is mostly for future reference and further thought

**Comment by arnfinn** [comment]
Removed Martina Hansens, Betanien and one more hospital (do not remember which one) from HF level.
