### ISSUE TITLE
Korrekt ruting av ideelle sykehus

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#49]
Jeg er usikker på hvordan vi skal rute de ideelle sykehusene. Dette gjelder både de med driftsavtale med RHFene med egen opptaksområde (Haraldsplass, Diakonhjemmet, Lovisenberg), men også andre private-ideelle sykehus som inngår i det regionale «sørge for ansvaret» (totalt tolv stykk, Martina Hansen etc.).

https://www.ssb.no/ajax/ordforklaring?key=297083&sprak=no

Alternativer
1. Rute de til Private sykehus, som nå. Haraldsplass, Diakonhjemmet og Lovisenberg rutes til seg selv
2. Lage nytt "HF" kalt "Private, ideelle institusjoner" eller lignende og rute alle hit (inkludert Haraldsplass, Diakonhjemmet og Lovisenberg). Dette HF rutes videre til Private på RHF-nivå.
3. Rute direkte til RHF-nivå, hvis dette er teknisk mulig i database. Jeg tror alle institusjonene ligger under et RHF.
4. Lage ~~fire~~ to (kun relevant for vest og sør-øst) nye HF som alle har samme kort-navn, men rutes til ulike RHF.
5. Lage ~~fire~~ to (kun relevant for vest og sør-øst) nye HF med ulike kortnavn som rutes til ulike RHF. 

Jeg ville stemt for alternativ 4, hvis det er teknisk mulig.

**Comment by arnfinn** [comment]
Somatikk
- Lovisenberg Diakonale Sykehus AS
- Diakonhjemmet Sykehus AS
- Stiftelsen Betanien Hospital Skien
- Martina Hansen Hospital AS
- Revmatismesykehuset AS
- Haugesund Sanitetsforenings Revmatismesykehus AS
- Haraldsplass Diakonale Sykehus AS
- Stiftelsen Betanien Bergen

Psykiatri
- NKS Jæren DPS AS
- Solli sykehus
- NKS Olaviken alderspsykiatriske sykehus AS
- Voss DPS NKS Bjørkeli AS

**Comment by arnfinn** [comment]
Jeg har endret litt på databasen, så HF ser nå slik ut:

![Screenshot from 2020-09-10 12-44-54](https://user-images.githubusercontent.com/136346/92719538-937d5d80-f363-11ea-98b9-5689a9ccf55e.png)

Endret følgende sykehus:

![Screenshot from 2020-09-10 12-44-05](https://user-images.githubusercontent.com/136346/92719561-9f691f80-f363-11ea-9931-555220562126.png)

**Comment by areedv** [comment]
Det der kan fungere, og om det skulle opptre noe slikt i HN og HM også så er det bare å legge til. Om jeg skulle være kritisk til noe så måte det være valg av orgnr som er til forveksling lik de som benyttes på Udefinerte organisasjoner. Og der gikk muligens starten på en nomenklatur-diskusjon for våre egen dummy oppføringer...

**Comment by arnfinn** [comment]
`333333` og `444444` ble valgt fordi vi i analyseenheten har brukt `3` for *Helse Vest RHF*, `4` for *Helse Sør-Øst RHF* i våre data. At jeg brukte seks siffer og ikke ni er litt tilfeldig. Ikke noe problem for meg hvis vi endrer på dette:)

**Comment by areedv** [comment]
Nå kræsjer lymfoid (bla på Diakonhjemmet). Jeg forsøker å endre tilbake, men da bare på orgnr på sykehusnivå og IKKE hvilket hf (444444), så får vi se...

**Comment by arnfinn** [comment]
Usikker på hva du mener. Hvilket orgnr er det snakk om?

**Comment by arnfinn** [comment]
Er det disse? 974116804, 974207532, 984027737

Enten så må disse endres i dataene til tilsvarende nummer på sykehusnivå, eller så må disse også legges inn som sykehus. Hvis sistnevnte så blir det to oppføringer på Lovisenberg etc.

**Comment by areedv** [comment]
Joda, det i data endringen må skje. Jeg fikser

**Comment by arnfinn** [comment]
Jeg fikset på det i går, så nå ligger lymfoid riktig inne
