### ISSUE TITLE
Error when trying to upload data for one user but not for another user

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#51]
Same data, same machine, different user (just logged out and logged in again).

First user (fails):
![Screenshot from 2020-09-11 11-09-46](https://user-images.githubusercontent.com/136346/92899950-90e03e00-f41f-11ea-8ab0-13cdc2eb9303.png)

Second user (OK):
![Screenshot from 2020-09-11 11-10-32](https://user-images.githubusercontent.com/136346/92900140-b5d4b100-f41f-11ea-9142-e01889b254a1.png)

**Comment by areedv** [comment]
Strange. [The size limit it a general setting in the server function](https://github.com/mong/imongr/blob/44ec9938421563460416c2cda534ebe3a9054fe4/R/app_server.R#L13), independent of user...

**Comment by areedv** [comment]
I'll try to reproduce the error in a dev env

**Comment by arnfinn** [comment]
It worked for the user `arnfinn.steindal@gmail.com` previously today (but not Yesterday), so kind of random.

Previously it did not work on one machine (windows), but worked on another (linux).

**Comment by areedv** [comment]
I cannot reproduce the error. Works like a charm bot in dev and at mongr.no. The file size is quite small and well below limit which makes the error even more strange....

**Comment by arnfinn** [comment]
It is not some special data. When my user get this error message, it is for all data.

**Comment by areedv** [comment]
Any error logs or console output as the error occurs would be useful...

**Comment by arnfinn** [comment]
@lenaringstado

**Comment by areedv** [comment]
I this still a problem?

**Comment by arnfinn** [comment]
Ja

**Comment by lenaringstado** [comment]
Jeg har lastet opp data mange ganger de siste par dagene og ikke hatt problemer med lasting av data .
Det var trøbbel med endring av indikatordefinisjoner/beskrivelser. Disse ble ikke oppdatert før Arnfinn hadde aggregert data på nytt. (Men det er vel ikke en del av denne saken...)

**Comment by arnfinn** [comment]
Har opplevd det av og til, men ikke så mye som tidligere. Nå har det fungert med en F5 og prøve på nytt.

**Comment by arnfinn** [comment]
Lenge siden sist jeg har opplevd dette.
