### ISSUE TITLE
Something wrong with dg

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#71]
Not possible to use `dummy_dg`, which is `1` for all `orgnr`. Not sure why.

**Comment by arnfinn** [comment]
Mulig grunn?: `dummy_dg` har `year == 2015`. Hvis 2015 ikke finnes i dataene vil kanskje ikke dekningsgraden legges på?

**Comment by arnfinn** [comment]
Jeg har nå lagt inn årene 2007, 2009, 2011, 2013, 2015, 2017 og 2019 i `dummy_dg`.

**Comment by areedv** [comment]
Nei, gamle dekningsgrader brukes ikke på nye data. Skjema er omtrent slik (fra kommentar i koden):
```r
# dg might not be present for every year, hence start filling in oldest
# and consecutively replace these with newer if present. Data older than
# the oldest dg will not be provided with a dg and will remain default (NA)
# at: temporary aggs for each iteration
# dt: temporary dg_data for each iteration
```

**Comment by arnfinn** [comment]
Er denne løst @areedv? Det så ikke ut til å fungere med nye `dummy_dg` heller, som jeg kan se.
