### ISSUE TITLE
Broken nkr_nakke data in db?

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#81]
I get the following error when I try to re-aggregate data (locally):

```
Aggregating nkr_nakke
...aggregating
Warning: Error in agg_udef: Got data where denominator difference is 0. This must be an error. Stopping!
  [No stack trace available]
```

**Comment by lenaringstado** [comment]
Nakke-data har fungert før og fungerer plutselig ikke nå? 
Feilmeldinga er merkelig. Hvorfor kan ikke differansen mellom to nevnere være 0?
Feilmeldinga sier ingenting om hvilken indikator det kan dreie seg om, så evt. må alle data hentes inn på nytt. Det kan vi kanskje vente med til det er mulig å vise 2020-data?

**Comment by arnfinn** [comment]
Litt usikker på hva det betyr, men jeg tror det har noe med at det er levert data på både HF og sykehus. Ser nå at denne issuen her kan være en duplikat av issue #74, som er fikset i branchen https://github.com/mong/imongr/compare/ver-0.15.

**Comment by lenaringstado** [comment]
Nye tall for dg nakke lagt inn.
