### ISSUE TITLE
Få opp imongr

### ISSUE THREAD

**Issue by areedv** [mong/imongr#94]
At gammel løsning for ruting av mongr.no fungerer for noen men ikke andre tror jeg skyldes mellomlagring i DNS-er der nye innstillnger avventer omlasting. Om vi er litt heldige fungerer det igjen for alle om en dag eller to

**Comment by arnfinn** [comment]
Fungerer hos meg nå.

**Comment by arnfinn** [comment]
Ser ikke ut til å fungere for alle.

**Comment by areedv** [comment]
Nå på nytt domene skde.org (og seinere til skde.no)
